### ISSUE TITLE
myq failing in HA version 0.37.1

### ISSUE THREAD

**Issue by turboc1208** [geekofweek/homeassistant#3]
This started failing about the time I got MQTT working.  I don't know if there is any correlation at all.  Can you take a look at this and try and point me in the right direction for what is going on.  Thanks

Here is the cover section of my configuration.yaml

cover:
  platform: myq
  name: Garage door Opener
  username: !secret myquser
  password: !secret myqpassword
  brand: liftmaster

I verified the username and password by logging into the myQ website.  I can still open and close my doors through wink, but not HA anymore.

```
17-02-09 20:19:35 INFO (MainThread) [homeassistant.loader] Loaded cover.myq from custom_components.cover.myq
17-02-09 20:19:35 INFO (MainThread) [homeassistant.bootstrap] Setting up cover
17-02-09 20:19:35 INFO (MainThread) [homeassistant.components.cover] Setting up cover.myq
17-02-09 20:19:36 ERROR (MainThread) [homeassistant.components.cover] Error while setting up platform myq
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/cover/myq.py", line 70, in setup_platform
    in myq.get_garage_doors())
  File "/home/homeassistant/.homeassistant/custom_components/cover/myq.py", line 153, in get_garage_doors
    devices = self.get_devices()
  File "/home/homeassistant/.homeassistant/custom_components/cover/myq.py", line 129, in get_devices
    self._logged_in = self.login()
  File "/home/homeassistant/.homeassistant/custom_components/cover/myq.py", line 120, in login
    auth = login.json()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
17-02-09 20:19:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=cover, service=open_cover>
17-02-09 20:19:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=cover, service=set_cover_tilt_position>
17-02-09 20:19:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=cover, service=stop_cover>
17-02-09 20:19:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=cover, service=close_cover>
17-02-09 20:19:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=cover, service=stop_cover_tilt>
17-02-09 20:19:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=cover, service=close_cover_tilt>
17-02-09 20:19:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=cover, service=set_cover_position>
17-02-09 20:19:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=cover, service=open_cover_tilt>
17-02-09 20:19:36 INFO (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=cover>
```

**Comment by geekofweek** [comment]
Check out [this](https://raw.githubusercontent.com/arraylabs/myq/master/myq.py).  Seems it broke and I didn't notice since it gets picked up by Wink as well.  


That is where I originally got the code from but modified it for the universal that worked with my setup.  I think that version now work with it.


You can find more details in [this thread](https://community.home-assistant.io/t/myq-componenet-issues/1860/208)
